name: Lint

on:
  push:
    branches-ignore: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
    -
      name: Set up Go 1.20
      uses: actions/setup-go@v1
      with:
        go-version: 1.20
    -
      name: Clone repository
      uses: actions/checkout@v2
    -
      name: Vendor modules
      run: make modules
    -
      name: Lint
      uses: golangci/golangci-lint-action@v2
      with:
        args: -v --timeout=5m
        skip-build-cache: true
        skip-go-installation: true
        skip-pkg-cache: true
